// Author: Mark Dalton Gray
// Display name: What secrets or certificates were created last month?
// Description: List of secrets and certificates created from the last 30 days.
// Categories: Security
// Resource types: Key vaults
// Topic: Usage and Diagnostics

AzureDiagnostics
| where TimeGenerated > ago(30d)
| where ResourceProvider == "MICROSOFT.KEYVAULT"
| where OperationName == "SecretCreate" or OperationName == "CertificateCreate"