// Author: Mark Dalton Gray
// Display name: What users are retrieving secrets?
// Description: Lists all users retrieving secrets in last day.
// Categories: Security
// Resource types: Key vaults
// Topic: Usage and Diagnostics

AzureDiagnostics
| where TimeGenerated > ago(1d)
| where ResourceProvider == "MICROSOFT.KEYVAULT"
| where OperationName == "SecretGet" and identity_claim_scp_s  == "user_impersonation"
| summarize count() by identity_claim_upn_s, CallerIPAddress, clientInfo_s | order by count_ desc